[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
async-trait = "0.1.83"
